Batching callback
mpetrovich/imagely pull request #9
Opened 2017-04-25 00:16 UTC by choshun

Site specific image batching callback.

2017-04-25 00:21 UTC, choshun commented on imagely.bin.js
This could use some work, but will allow us to test easier.

2017-05-02 13:47 UTC, mpetrovich commented on imagely.bin.js
> +				var name = this.destination.split('/').slice(-1).pop();
For filepath parsing, use Node's built-in `path` methods:
```js
var name = path.basename(this.destination);
```
You'll need to `var path = require('path');` above but don't need to `yarn add` anything—`path` is a native Node package.

2017-05-02 15:03 UTC, mpetrovich commented on imagely.bin.js
> +				uniqueName = this.destination.replace(name, json[0].key + '.gif');
`key` is a very non-obvious and non-descriptive property. Consider `filename`

2017-05-31 19:28 UTC, mpetrovich commented on imagely.bin.js
> +	fs.writeFile(logFilepath, JSON.stringify(logs, 0, 4), function(err) {
The parameters passed to `JSON.stringify()` don't look correct: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

2017-05-31 19:35 UTC, mpetrovich commented on imagely.bin.js
> +			var name = this.destination.split('/').slice(-1).pop();
This isn't a platform-compatible way to parse filepaths (eg. on Windows the delimiter isn't `/`). Use the node `path` module instead (eg. `path.basename()`).

2017-05-31 19:36 UTC, mpetrovich commented on imagely.bin.js
> +			uniqueName = this.destination.replace(name, json[0].key + '.gif');
Consider declaring and assigning `uniqueName` at the same time

2017-05-31 19:38 UTC, mpetrovich requested changes
Needs a few changes. In addition, could you add some more color to the description around what you're doing and why? Coming back to this in the future (and even now after being away from it for a few weeks), it's hard to understand what this is trying to accomplish.

2017-05-31 19:40 UTC, mpetrovich commented on imagely.bin.js
> +	log['endpoint'] = imageKeyArray[0];
Prefer object property syntax: `log.uuid = `, etc.

2017-05-31 19:40 UTC, mpetrovich commented on imagely.bin.js
> +	log['endpoint'] = imageKeyArray[0];
"endpoint" is _very_ NBS specific.

2017-05-31 23:16 UTC, choshun commented on imagely.bin.js
> +	fs.writeFile(logFilepath, JSON.stringify(logs, 0, 4), function(err) {
Looks like for both "replacer" and "space" optional params you can use a number, this is identical to `JSON.stringify(logs, null, '\t')`.

I can change to be more readable if you want.

2017-05-31 23:18 UTC, choshun commented on imagely.bin.js
> +			var name = this.destination.split('/').slice(-1).pop();
Thanks, good to know. Changed.

2017-05-31 23:18 UTC, choshun commented on imagely.bin.js
> +			uniqueName = this.destination.replace(name, json[0].key + '.gif');
Yup, changed.

2017-05-31 23:27 UTC, choshun commented on imagely.bin.js
> +	log['endpoint'] = imageKeyArray[0];
I think this whole commit is very site specific (hence commit message), which sort of brings up a broader point of maybe having this be in a separate branch, or passing in the callback altogether from the code base. I feel like this file should literally just be setting options and instantiating Imagely with options and a user set callback.

Not sure the cleanest way to do this.

2017-05-31 23:32 UTC, choshun commented
Sure, going back to my last comment, I really think this file shouldn't need explanation, and too much site specific stuff is in here in retrospect. I can add comments, but they will be very descriptive of a problem that isn't necessarily a responsibility of Imagely.

2017-05-31 23:37 UTC, mpetrovich commented on imagely.bin.js
> +	fs.writeFile(logFilepath, JSON.stringify(logs, 0, 4), function(err) {
the `0` threw me off—it's supposed to be `null`, a function, or an array. Why do you need to pretty print it?

2017-05-31 23:44 UTC, choshun commented on imagely.bin.js
> +				uniqueName = this.destination.replace(name, json[0].key + '.gif');
Woops, missed this.

Sure, will change for clarity.

2017-06-01 17:19 UTC, choshun commented on imagely.bin.js
> +	fs.writeFile(logFilepath, JSON.stringify(logs, 0, 4), function(err) {
I guess it's an old habit, changed to `null`.

2017-06-08 21:20 UTC, mpetrovich approved these changes

2017-06-08 21:20 UTC, merged